name: Upload Website - Prod

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ["14"]
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Installs yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install 
      - name: Builds sources
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build 
      - name: Deploys sources to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1" # optional: defaults to us-east-1
          SOURCE_DIR: "dist" # optional: defaults to entire repository
      - name: publish to github packages
        uses: borales/actions-yarn@v2.0.0
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url: PACKAGE-REGISTRY.pkg.github.com
          cmd: publish 
