name: Upload Website - Dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [10.x, 12.x, 14.x]
    name: build & test
    steps:
      - uses: actions/checkout@v2
      - name: Installs dependencies
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run-script build        
     
  deploy:
    needs: [build]
    runs-on: ubuntu-18.04
    name: deploy to s3
    steps:
      - uses: actions/checkout@v2
      - name: Installs dependencies
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run-script build        
      - name: Deploys sources to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1" # optional: defaults to us-east-1
          SOURCE_DIR: "dist" # optional: defaults to entire repository